// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRJK5_JNMl7mfBLdjD08TF0L_loWVu1rQ',
    appId: '1:248789009191:web:034505ed0369f344af1f02',
    messagingSenderId: '248789009191',
    projectId: 'tarashly-e3a36',
    authDomain: 'tarashly-e3a36.firebaseapp.com',
    storageBucket: 'tarashly-e3a36.appspot.com',
    measurementId: 'G-8J86GCJ95D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEh2GbVgq3D0C5s61WNXdlP6x7E8D4wgk',
    appId: '1:248789009191:android:636124e51e0d1e40af1f02',
    messagingSenderId: '248789009191',
    projectId: 'tarashly-e3a36',
    storageBucket: 'tarashly-e3a36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNnHKk_Cx5GIQHXD212WWx4Vvuh3NiDHk',
    appId: '1:248789009191:ios:896e7207480f6caeaf1f02',
    messagingSenderId: '248789009191',
    projectId: 'tarashly-e3a36',
    storageBucket: 'tarashly-e3a36.appspot.com',
    iosBundleId: 'com.example.flutterApplication1Day4',
  );
}
